CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS feeddb;
CREATE DATABASE IF NOT EXISTS followdb;
CREATE DATABASE IF NOT EXISTS postdb;
CREATE DATABASE IF NOT EXISTS user_service_db;
